---
- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers, apps
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask
    
  roles:
    - app
